### ISSUE TITLE
Missing payload validation?

### ISSUE THREAD

**Issue by yosriady** [comit-network/comit-js-sdk#230]
## Problem

cnd does not validate asset quantities and it is possible to create a swap where both quantities are null.

<details>
<summary>Original Content</summary>
Unexpectedly, I can create 0-for-0 swaps. Is this expected?

```
parameters: {
	alpha_asset: {
		name: "erc20",
		quantity: "0",
		token_contract: "0x62d69f6867a0a084c6d313943dc22023bc263691"
	},
	alpha_ledger: {
		chain_id: 17,
		name: "ethereum",
		network: "regtest"
	},
	beta_asset: {
		name: "bitcoin",
		quantity: "0"
	},
	beta_ledger: {
		name: "bitcoin",
		network: "regtest"
	}
}
```

I would expect payloads like this to be rejected by the protocol.
</details>

## Goal

Validate that quantities not null at swap creation on both old and new routes.

Out of scope: Further validation, validate that quantity are "big enough", etc.

**Comment by bonomat** [comment]
You are right, we do not reject 0-for-0 swaps. 
While I feel like this should be caught from a UI I think rejecting this on cnd side would be easy.

@D4nte any thoughts on this?

**Comment by yosriady** [comment]
I think cnd should reject payloads which are clearly invalid (invalid types, invalid ranges, invalid token pairs, etc.) The client nor the SDK wouldn't know what qualifies as valid or invalid.

**Comment by D4nte** [comment]
Pinging @thomaseizinger too.

Regarding validation, there are a lot of possibilities to review and it can be hard to do an exhaustive coverage.
Note that invalid types ranges and pair are already rejected.
We could have a check to ensure that the asset is not 0.

I would be against adding a check to ensure that the asset is not "too small" because it would simply take some effort to calculate that.

**Comment by thomaseizinger** [comment]
> Pinging @thomaseizinger too.
> 
> Regarding validation, there are a lot of possibilities to review and it can be hard to do an exhaustive coverage.
> Note that invalid types ranges and pair are already rejected.
> We could have a check to ensure that the asset is not 0.
> 
> I would be against adding a check to ensure that the asset is not "too small" because it would simply take some effort to calculate that.

Agreed, happy to reject swaps with amount 0.

**Comment by yosriady** [comment]
When validating the range, it should also validate against negative numbers, not just 0.

If you're using JSON Schema, you can use https://json-schema.org/understanding-json-schema/reference/numeric.html#range

**Comment by thomaseizinger** [comment]
@D4nte If you are going to tag this as `good-first-issue` please refine the ticket text accordingly so it is friendly to new-comers :)
Terms like "old and new routes" are not something an external person will understand :grimacing:. We should probably point out the places in the code that need to be modified and that the change should likely be accompanied by e2e tests.

I would decide against JSON schema for now because it is non-trivial to decide how it interacts with deserialization using serde and the validation that already happens as part of that.

**Comment by D4nte** [comment]
Issue moved to [comit-network/comit-rs #2572](https://github.com/comit-network/comit-rs/issues/2572) via [**ZenHub**](https://www.zenhub.com/)
